# Generated by Django 4.1.7 on 2023-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.SlugField(max_length=100)),
                ('position', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='blogs/%Y/%m/%d')),
                ('short_descr', models.TextField(max_length=100)),
                ('descr_paragraph1', models.TextField(blank=True, max_length=200)),
                ('descr_paragraph2', models.TextField(blank=True, max_length=200)),
                ('descr_paragraph3', models.TextField(blank=True, max_length=200)),
                ('descr_paragraph4', models.TextField(blank=True, max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
